config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :chat_rooms, only: [:new, :create, :show, :index]
  root 'chat_rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  validates :body, presence: true, length: {minimum: 1, maximum: 250}
  after_create_commit do
    MessageBroadcastJob.perform_later(self)
  end

def timestamp
  created_at.strftime('%H:%M:%S %d %B %Y')
end


end

app/models/user.rb
class User < ApplicationRecord

  has_many :chat_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


def name
  email.split('@')[0]
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
   def index
    @chat_rooms = ChatRoom.all
  end

  def new
    @chat_room = ChatRoom.new
  end

  def create
    @chat_room = current_user.chat_rooms.build(chat_room_params)
    if @chat_room.save
      flash[:success] = 'Chat room added!'
      redirect_to chat_rooms_path
    else
      render 'new'
    end
  end

  def show
  @chat_room = ChatRoom.includes(:messages).find_by(id: params[:id])
  @message = Message.new
  end

  private

  def chat_room_params
    params.require(:chat_room).permit(:title)
  end



end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  # def gravatar_for(user, opts = {})
  #   opts[:alt] = user.name
  #   image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
  #             opts
  # end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title}", chat_room_path(chat_room) %></li>

app/views/chat_rooms/index.html.erb
<div class='loginout'>
<% if user_signed_in? %>
  <h1><%= current_user.name.capitalize %></h1>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>
</div>

<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @chat_rooms %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, class: 'form-control' %>
  </div>

  <%= f.submit "Add!", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css" rel="stylesheet"

<div class="container">
  <h1 class="text-center"><%= @chat_room.title %></h1>

<div class="messaging text-center">



<div class="mesgs">
  <div id="messages" class="msg_history" data-chat-room-id="<%= @chat_room.id %>">
  <%= render @chat_room.messages %>
  </div>
</div>
</div>

<%= form_for @message, url: '#', class:'type_msg' do |f| %>
  <%= hidden_field_tag 'chat_room_id', @chat_room.id %>
  <div class="form-group input_msg_write">
    <%= f.text_area :body, class: 'form-control write_msg', placeholder:'Type a message From 2 to 250 characters'%>
  </div>

  <%= button_tag(class: 'btn btn-primary btn-lg') do %>
  Post <i class="fa fa-paper-plane-o" aria-hidden="true"></i>
  <% end %>
    </div>
          </div>
        </div>
      </div>
  <%= link_to 'Back', :back , class: 'btn btn-primary btn-lg'%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlatChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="outgoing_msg">
  <div class=""><strong><%= message.user.name.capitalize %></strong></div>
    <div class="received_msg">
      <div class="sent_msg">
        <p><%= message.body %></p>
            <span class="time_date"><%= message.timestamp %></span>
      </div>
    </div>
    </div>